[workspace]
resolver = "2"

members = [
"client",
"server",
"lib",
]

# Enable a small amount of optimization in debug mode
[profile.dev]
opt-level = 1
debug = true

# Enable high optimizations for dependencies (incl. Bevy), but not for our code:
[profile.dev.package."*"]
opt-level = 3
